#!/usr/bin/env python

# Load .env.json keys as environmental variables for
# for local development.

import os
import sys
import subprocess
import json

data = json.load(open('.env.json', 'r'))
for key, value in data.items():
    if isinstance(value, dict):
        value = json.dumps(value)
    os.environ[key] = value

try:
    subprocess.run(' '.join(sys.argv[1:]), shell=True)
except KeyboardInterrupt:
    pass